# Generated by Django 5.0.6 on 2024-06-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creation_by', models.TextField()),
                ('updation_date', models.DateTimeField(auto_now=True, null=True)),
                ('updation_by', models.TextField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid_user', models.UUIDField()),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_id', models.TextField()),
                ('password_hash', models.TextField()),
                ('gender', models.IntegerField()),
            ],
            options={
                'db_table': 'sm_user_model',
                'ordering': ('-creation_date',),
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('refresh_token', models.TextField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='refresh_user', to='social_user_management.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='FriendModel',
            fields=[
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('creation_by', models.TextField()),
                ('updation_date', models.DateTimeField(auto_now=True, null=True)),
                ('updation_by', models.TextField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('friend_user_name', models.CharField(max_length=255)),
                ('friend_user_uuid', models.TextField()),
                ('friend_email_id', models.TextField()),
                ('friend_acceptance_status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_friend', to='social_user_management.usermodel')),
            ],
            options={
                'db_table': 'sm_friend_model',
                'ordering': ('-creation_date',),
            },
        ),
    ]
