# Generated by Django 5.0.6 on 2024-06-04 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='uuid_user',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
