# Generated by Django 5.0.6 on 2024-06-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_user_management', '0002_alter_usermodel_uuid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='uuid_user',
            field=models.TextField(unique=True),
        ),
    ]
