# Generated by Django 5.0.6 on 2024-06-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_user_management', '0003_alter_usermodel_uuid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendmodel',
            name='friend_acceptance_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
